name: Deploy

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main

jobs:
  test:
    name: Unit Tests
    uses: ./.github/workflows/test.yml

  outputs:
    name: Set outputs
    uses: ./.github/workflows/outputs.yml

  deploy:
    name: Deploy to Netlify
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, 'skip ci')"

    env:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

    needs:
      - outputs
      - test

    outputs:
      deploy_id: ${{ steps.deploy.outputs.deploy_id }}
      deploy_url: ${{ steps.deploy.outputs.deploy_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install Netlify CLI
        run: |
          npm i -g netlify-cli

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true
          cache-dependency-path: |
            go.sum

      - name: Update version
        run: |
          version="$(echo ${{ needs.outputs.outputs.version }} | sed 's|v||' )"
          sed -i 's|version: "[0-9.]*[-a-zA-Z0-9]*"|version: "'"$version"'"|' api_v1.yml

          if ${{ github.ref != 'refs/heads/main' }}; then
            sed -i 's|https://go-baas.netlify.app|https://${{ needs.outputs.outputs.short_sha }}-go-baas.netlify.app|' api_v1.yml
          fi

      - name: Set deploy variables
        id: var
        run: |
          deploy_message="${{ needs.outputs.outputs.short_sha }} - ${{ needs.outputs.outputs.message }}"

          prod_flag=""
          alias_flag="--alias=${{ needs.outputs.outputs.short_sha }}"

          if ${{ github.ref == 'refs/heads/main' }}; then
            prod_flag="--prod"
            alias_flag=""
          fi

          echo "deploy_message=$deploy_message" >> $GITHUB_OUTPUT
          echo "prod_flag=$prod_flag" >> $GITHUB_OUTPUT
          echo "alias_flag=$alias_flag" >> $GITHUB_OUTPUT

      - name: Deploy
        id: deploy
        run: |
          netlify deploy \
            --build \
            ${{ steps.var.outputs.prod_flag }} \
            ${{ steps.var.outputs.alias_flag }} \
            --message="${{ steps.var.outputs.deploy_message }}" \
            --telemetry-disable \
            --json \
            > netlify.json

          echo "deploy_id=$(jq -r '.deploy_id' netlify.json)" >> $GITHUB_OUTPUT
          echo "deploy_url=$(jq -r '.deploy_url' netlify.json)" >> $GITHUB_OUTPUT

  comment:
    name: Comment on PR
    needs:
      - deploy
    permissions:
      pull-requests: write
    uses: ./.github/workflows/comment.yml
    with:
      netlify_deploy_id: ${{ needs.deploy.outputs.deploy_id }}
      netlify_deploy_url: ${{ needs.deploy.outputs.deploy_url }}
